#!/bin/bash

# this script should be triggered to run with ( crontab -e )
# it will fail if it's not executable (chmod +x run)
# 0 * * * * /home/pi/run

# rotate the log file
cat lastrun.log >> everyrun.log

# stderr to stdout and stdout to file
sh ./karen.sh > ./lastrun.log 2>&1
