#!/bin/bash -i
cd "${0%/*}"

# one-click install..., ya bish?
echo "===================================="
echo "INSTALLER SCRIPT FOR COMPASS SCRAPER"





# SYSTEM INSTALL
echo
echo ###################
cmds="
sudo apt update -y
sudo apt upgrade -y

sudo apt-get install chromium-chromedriver -y
"
asktoinstall "$cmds"




# MAC ONLY
echo
echo ###################
echo "if running on Mac OS, run this"
cmds="
python3 -m pip install --upgrade pip
"
asktoinstall "$cmds"




# PYTHON
echo
echo ###################
echo "setup python environment"
cmds="
sudo apt-get install python3-venv -y
python3 -m venv venv
. venv/bin/activate
pip install bs4 selenium lxml requests
pip3 install webdriver_manager
"
asktoinstall "$cmds"





# RUN SETUP OTHER SCRIPTS
echo
echo ###################
echo "set alert email address?"
cmds="
python3 setup_toList.py
"
asktoinstall "$cmds"


# CRONTAB
echo
echo ###################
echo "NOW, SETUP CRONTAB:"
echo
echo "crontab -e"
echo
echo "...paste in this:"
# TODO CLUNKLY... DON'T HARD CODE SHIT
echo "0 * * * * /home/pi/compassScraper/run"
