#!/bin/bash -i
cd "${0%/*}"

# one-click install..., ya bish?
echo "===================================="
echo "INSTALLER SCRIPT FOR COMPASS SCRAPER"


# ASSUME THE USER HAS DONE THIS IF NEEDED... AT THE VERY VERY BEGINNING... VIA .INSTALLDOT
# sudo apt upgrade -y

# SYSTEM INSTALL
echo
echo ###################
cmds="
sudo apt update -y

sudo apt-get install chromium-chromedriver -y
"
asktoinstall "$cmds"



# MAC ONLY
if [[ $(uname -a) == *"Dawrin"* ]]; then
    echo
    echo ###################
    echo LOOKS LIKE YOURE RUNNING ON MAC OS...
    echo YOU NEED THIS!
    cmds="
    python3 -m pip install --upgrade pip
    "
    asktoinstall "$cmds"
fi


# TODO HOW TO ACTUATE THE VENV IN A MODULE???
#python3 -m venv venv
#. venv/bin/activate

# PYTHON
echo
echo ###################
echo "setup python environment"
cmds="
pip install bs4 selenium lxml requests
pip3 install webdriver_manager
"
asktoinstall "$cmds"





# RUN SETUP OTHER SCRIPTS
echo
echo ###################
echo "set alert email address?"
cmds="
python3 setup_toList.py
"
asktoinstall "$cmds"


# CRONTAB
echo
echo ###################
echo "NOW, SETUP CRONTAB:"
echo
echo "crontab -e"
echo
echo "...paste in this:"
# TODO CLUNKLY... DON'T HARD CODE SHIT
echo "0 * * * * /home/pi/compassScraper/run"
